// Search index - flat array of all articles for fast search
// Auto-generated from main.js articlesData
const searchData = [
  // ===== telekom / news =====
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  // ===== telekom / technology =====
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  // ===== telekom / tarife =====
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  // ===== mobilfunk / sim-types =====
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  // ===== mobilfunk / prepaid =====
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  // ===== mobilfunk / tips =====
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  // ===== anbieter / o2 =====
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  // ===== anbieter / blau =====
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  // ===== anbieter / vodafone =====
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  // ===== anbieter / weitere =====
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
  "image": "images/default-article.jpg",
];
